// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASSrnakY8SByZHAp4JrjI6Uu5ZmFvM3bM',
    appId: '1:590073059161:web:23c5966216a687862b9e48',
    messagingSenderId: '590073059161',
    projectId: 'flutter-firebase-movies',
    authDomain: 'flutter-firebase-movies.firebaseapp.com',
    storageBucket: 'flutter-firebase-movies.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJYlTkQFvQdfGa48XcSzQgE252M84k5sU',
    appId: '1:590073059161:android:3b223f3481fbfedf2b9e48',
    messagingSenderId: '590073059161',
    projectId: 'flutter-firebase-movies',
    storageBucket: 'flutter-firebase-movies.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAd1gM7Pgewop0-245ivkF3K__13dQ2vxI',
    appId: '1:590073059161:ios:526e3ba920bd67a72b9e48',
    messagingSenderId: '590073059161',
    projectId: 'flutter-firebase-movies',
    storageBucket: 'flutter-firebase-movies.appspot.com',
    iosClientId:
        '590073059161-jaf3ot4n6tl9cke206a7cv0evl3falj7.apps.googleusercontent.com',
    iosBundleId: 'com.flutterFirebase',
  );
}
